server:
  port: 9435

simbot:
  bot-configuration-resources:
    - 'classpath:simbot-bots/*.bot*' # 资源路径中的文件
    - 'file:simbot-bots/*.bot*'      # 本地文件系统中的文件

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:E:/GitProject/Bilibili-QQ-BOT/src/main/resources/db/history.db
    url: jdbc:sqlite::resource:db/history.db

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 打印SQL语句
#logging:
#  level:
#    top.keithfeng.mapper: debug

# 设置需要订阅的主播和群号
bilibili:
  # 主播的UID
  uid: 1566071
  # 推送消息的群号，有多个群号以半角逗号(,)分隔
  group: 1030444096
  # 直播间ID
  room: 28464

# 设置何时@全体成员
notify-all:
  # 动态
  dynamic: false
  # 开播提醒
  live-on: true
  # 下播提醒
  live-off: false

# ChatGPT APIKey
gpt:
  use-api2d: true
  api-key: